### PR TITLE
Rectified spelling mistake in README.md file

### LINKED ISSUE #383: doc: ...
Hello Kaskada team,

There is a spelling mistake in README.md file. I am opening an issue for that, will rectify the spelling mistake, create a pull request.

Thank you.

### PR DESCRIPTION
**Pull request by sachelsout**
Close #383

### CODE REVIEW

**Review by kevinjnguyen — APPROVED** [review]
Good catch. Thanks for reporting the issue + fixing it 👍🏻

**Comment by sachelsout** [comment]
> Good catch. Thanks for reporting the issue + fixing it 👍🏻

Always a pleasure, Kevin !! :)

**Comment by sachelsout** [comment]
image

Hi Kevin, there are 7 workflows which needs maintainer's approval to merge the pull request successfully. Do let me know if I need to do anything from my end.

**Comment by kevinjnguyen** [comment]
> Hi Kevin, there are 7 workflows which needs maintainer's approval to merge the pull request successfully. Do let me know if I need to do anything from my end.

Good catch. I missed clicking "approve and run" on the pipeline. This should auto merge now.

**Comment by sachelsout** [comment]
> > Hi Kevin, there are 7 workflows which needs maintainer's approval to merge the pull request successfully. Do let me know if I need to do anything from my end.
> 
> Good catch. I missed clicking "approve and run" on the pipeline. This should auto merge now.

Thank you so much !!

**Comment by epinzur** [comment]
Thank you for your contribution to the Kaskada open source project. We appreciate your effort in finding the problem and providing a fix, however we cannot accept outside contributions at this time due to the absence of an Individual Contributor License Agreement (ICLA) for the project. Therefore we will have to close the PR.

We expect to have an ICLA available soon, and we look forward to collaborating with you in the future.

**Comment by sachelsout** [comment]
> Thank you for your contribution to the Kaskada open source project. We appreciate your effort in finding the problem and providing a fix, however we cannot accept outside contributions at this time due to the absence of an Individual Contributor License Agreement (ICLA) for the project. Therefore we will have to close the PR.
> 
> We expect to have an ICLA available soon, and we look forward to collaborating with you in the future.

Thank you for letting me know, Eric. Have a good day !!

**Pull request closed without merging**
